version: "3"

services:
  rproxy:
    image: pretorh/https-reverse-proxy
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./.private:/opt/rproxy/private
      - ./sites:/etc/nginx/conf.d/sites/
