name: Lint shell scripts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup ShellCheck
      shell: bash
      run: |
        curl -Lso shellcheck.tar.xz https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
        tar -xf shellcheck.tar.xz shellcheck-stable/shellcheck --strip-components 1

    - name: ShellCheck
      shell: bash
      run: ./shellcheck -f gcc $(find . -type f -name '*.sh')
